CD..
MKDIR "CARPETAS"
CD "CARPETAS"
MKDIR "RISARALDA","QUINDIO","TOLIMA"
CD "RISARALDA"
MKDIR "SEM"
CD "SEM"
MKDIR "HCB BELEN","HCB VIRGINIA","REFRIGERIOS VIRGINIA"
CD "HCB VIRGINIA"
MKDIR "MARTES A LUNES (Resto Municipios)","JUEVES A MIERCOLES (Balboa)"
CD..
CD..
CD..
CD "QUINDIO"
MKDIR "SEM"
CD "SEM"
MKDIR "CDI QUINDIO","REFRIGERIOS QUINDIO"
CD..
CD..
CD "TOLIMA"
MKDIR "SEM"
CD "SEM"
MKDIR "CDI MELGAR","HCB MELGAR","INPEC IBAGUE","REFRIGERIOS IBAGUE","REFRIGERIOS MELGAR"